# Generated by Django 4.2.13 on 2024-06-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('link', models.URLField()),
                ('sub', models.CharField(max_length=100)),
                ('msg', models.TextField()),
            ],
        ),
    ]
